checks:
  python:
    code_rating: true
    duplicate_code: true
build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - py-scrutinizer-run
          - command: pylint-run
            use_website_config: true
  dependencies:
    before:
      - sudo apt-get update
  environment:
    python:
      version: "3.8.0"
filter:
  excluded_paths:
    - '*/test/*'
  dependency_paths:
    - 'lib/*'
